package com.galaxyrio.sudokusolver.ui.screens.tutorial

import androidx.annotation.StringRes
import com.galaxyrio.sudokusolver.R
import com.galaxyrio.sudokusolver.domain.solver.TechniqueId

internal data class AdvancedLessonCopy(@param:StringRes val rule: Int, @param:StringRes val reason: Int, @param:StringRes val tip: Int)

/** Original explanations for detector variants and the reference lessons listed in NOTICE. */
internal fun advancedLessonCopy(technique: TechniqueId): AdvancedLessonCopy = when (technique) {
    TechniqueId.POINTING_PAIR -> AdvancedLessonCopy(
        R.string.tutorial_rule_pointing_pair, R.string.tutorial_reason_pointing_pair, R.string.tutorial_tip_pointing_pair)
    TechniqueId.POINTING_TRIPLE -> AdvancedLessonCopy(
        R.string.tutorial_rule_pointing_triple, R.string.tutorial_reason_pointing_triple, R.string.tutorial_tip_pointing_triple)
    TechniqueId.CLAIMING_PAIR -> AdvancedLessonCopy(
        R.string.tutorial_rule_claiming_pair, R.string.tutorial_reason_claiming_pair, R.string.tutorial_tip_claiming_pair)
    TechniqueId.CLAIMING_TRIPLE -> AdvancedLessonCopy(
        R.string.tutorial_rule_claiming_triple, R.string.tutorial_reason_claiming_triple, R.string.tutorial_tip_claiming_triple)
    TechniqueId.X_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_x_wing, R.string.tutorial_reason_x_wing, R.string.tutorial_tip_x_wing)
    TechniqueId.SWORDFISH -> AdvancedLessonCopy(
        R.string.tutorial_rule_swordfish, R.string.tutorial_reason_swordfish, R.string.tutorial_tip_swordfish)
    TechniqueId.JELLYFISH -> AdvancedLessonCopy(
        R.string.tutorial_rule_jellyfish, R.string.tutorial_reason_jellyfish, R.string.tutorial_tip_jellyfish)
    TechniqueId.FINNED_X_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_finned_x_wing, R.string.tutorial_reason_finned_x_wing, R.string.tutorial_tip_finned_x_wing)
    TechniqueId.FINNED_SWORDFISH -> AdvancedLessonCopy(
        R.string.tutorial_rule_finned_swordfish, R.string.tutorial_reason_finned_swordfish, R.string.tutorial_tip_finned_swordfish)
    TechniqueId.FINNED_JELLYFISH -> AdvancedLessonCopy(
        R.string.tutorial_rule_finned_jellyfish, R.string.tutorial_reason_finned_jellyfish, R.string.tutorial_tip_finned_jellyfish)
    TechniqueId.SKYSCRAPER -> AdvancedLessonCopy(
        R.string.tutorial_rule_skyscraper, R.string.tutorial_reason_skyscraper, R.string.tutorial_tip_skyscraper)
    TechniqueId.TWO_STRING_KITE -> AdvancedLessonCopy(
        R.string.tutorial_rule_two_string_kite, R.string.tutorial_reason_two_string_kite, R.string.tutorial_tip_two_string_kite)
    TechniqueId.TURBOT_CRANE -> AdvancedLessonCopy(
        R.string.tutorial_rule_crane, R.string.tutorial_reason_crane, R.string.tutorial_tip_crane)
    TechniqueId.EMPTY_RECTANGLE -> AdvancedLessonCopy(
        R.string.tutorial_rule_empty_rectangle, R.string.tutorial_reason_empty_rectangle, R.string.tutorial_tip_empty_rectangle)
    TechniqueId.XY_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_xy_wing, R.string.tutorial_reason_xy_wing, R.string.tutorial_tip_xy_wing)
    TechniqueId.XYZ_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_xyz_wing, R.string.tutorial_reason_xyz_wing, R.string.tutorial_tip_xyz_wing)
    TechniqueId.WXYZ_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_wxyz_wing, R.string.tutorial_reason_wxyz_wing, R.string.tutorial_tip_wxyz_wing)
    TechniqueId.FIVE_Y_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_five_y_wing, R.string.tutorial_reason_five_y_wing, R.string.tutorial_tip_five_y_wing)
    TechniqueId.SIX_Y_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_six_y_wing, R.string.tutorial_reason_six_y_wing, R.string.tutorial_tip_six_y_wing)
    TechniqueId.SEVEN_Y_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_seven_y_wing, R.string.tutorial_reason_seven_y_wing, R.string.tutorial_tip_seven_y_wing)
    TechniqueId.W_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_w_wing, R.string.tutorial_reason_w_wing, R.string.tutorial_tip_w_wing)
    TechniqueId.SIMPLE_COLORING_TYPE_1 -> AdvancedLessonCopy(
        R.string.tutorial_rule_coloring_1, R.string.tutorial_reason_coloring_1, R.string.tutorial_tip_coloring_1)
    TechniqueId.SIMPLE_COLORING_TYPE_2 -> AdvancedLessonCopy(
        R.string.tutorial_rule_coloring_2, R.string.tutorial_reason_coloring_2, R.string.tutorial_tip_coloring_2)
    TechniqueId.X_CHAIN -> AdvancedLessonCopy(
        R.string.tutorial_rule_x_chain, R.string.tutorial_reason_x_chain, R.string.tutorial_tip_x_chain)
    TechniqueId.X_CHAIN_LOOP -> AdvancedLessonCopy(
        R.string.tutorial_rule_x_chain_loop, R.string.tutorial_reason_x_chain_loop, R.string.tutorial_tip_x_chain_loop)
    TechniqueId.X_CHAIN_ONE_ENDPOINT -> AdvancedLessonCopy(
        R.string.tutorial_rule_x_chain_endpoint, R.string.tutorial_reason_x_chain_endpoint, R.string.tutorial_tip_x_chain_endpoint)
    TechniqueId.GROUPED_X_CHAIN -> AdvancedLessonCopy(
        R.string.tutorial_rule_grouped_x_chain, R.string.tutorial_reason_grouped_x_chain, R.string.tutorial_tip_grouped_x_chain)
    TechniqueId.THREE_D_MEDUSA -> AdvancedLessonCopy(
        R.string.tutorial_rule_medusa, R.string.tutorial_reason_medusa, R.string.tutorial_tip_medusa)
    TechniqueId.XY_CHAIN -> AdvancedLessonCopy(
        R.string.tutorial_rule_xy_chain, R.string.tutorial_reason_xy_chain, R.string.tutorial_tip_xy_chain)
    TechniqueId.XY_CHAIN_LOOP -> AdvancedLessonCopy(
        R.string.tutorial_rule_xy_chain_loop, R.string.tutorial_reason_xy_chain_loop, R.string.tutorial_tip_xy_chain_loop)
    TechniqueId.AIC -> AdvancedLessonCopy(
        R.string.tutorial_rule_aic, R.string.tutorial_reason_aic, R.string.tutorial_tip_aic)
    TechniqueId.NISHIO_FORCING_CHAIN -> AdvancedLessonCopy(
        R.string.tutorial_rule_nishio, R.string.tutorial_reason_nishio, R.string.tutorial_tip_nishio)
    TechniqueId.CELL_FORCING_CHAIN -> AdvancedLessonCopy(
        R.string.tutorial_rule_cell_chain, R.string.tutorial_reason_cell_chain, R.string.tutorial_tip_cell_chain)
    TechniqueId.REGION_FORCING_CHAIN -> AdvancedLessonCopy(
        R.string.tutorial_rule_region_chain, R.string.tutorial_reason_region_chain, R.string.tutorial_tip_region_chain)
    TechniqueId.CELL_FORCING_NET -> AdvancedLessonCopy(
        R.string.tutorial_rule_cell_net, R.string.tutorial_reason_cell_net, R.string.tutorial_tip_cell_net)
    TechniqueId.REGION_FORCING_NET -> AdvancedLessonCopy(
        R.string.tutorial_rule_region_net, R.string.tutorial_reason_region_net, R.string.tutorial_tip_region_net)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_1 -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur1, R.string.tutorial_reason_ur1, R.string.tutorial_tip_ur1)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_2 -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur2, R.string.tutorial_reason_ur2, R.string.tutorial_tip_ur2)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_3 -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur3, R.string.tutorial_reason_ur3, R.string.tutorial_tip_ur3)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_4 -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur4, R.string.tutorial_reason_ur4, R.string.tutorial_tip_ur4)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_5 -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur5, R.string.tutorial_reason_ur5, R.string.tutorial_tip_ur5)
    TechniqueId.BUG_PLUS_ONE -> AdvancedLessonCopy(
        R.string.tutorial_rule_bug, R.string.tutorial_reason_bug, R.string.tutorial_tip_bug)
    TechniqueId.LAST_DIGIT -> AdvancedLessonCopy(
        R.string.tutorial_rule_last_digit, R.string.tutorial_reason_last_digit, R.string.tutorial_tip_last_digit)
    TechniqueId.LOCKED_PAIR -> AdvancedLessonCopy(
        R.string.tutorial_rule_locked_pair, R.string.tutorial_reason_locked_pair, R.string.tutorial_tip_locked_pair)
    TechniqueId.LOCKED_TRIPLE -> AdvancedLessonCopy(
        R.string.tutorial_rule_locked_triple, R.string.tutorial_reason_locked_triple, R.string.tutorial_tip_locked_triple)
    TechniqueId.REMOTE_PAIR -> AdvancedLessonCopy(
        R.string.tutorial_rule_remote_pair, R.string.tutorial_reason_remote_pair, R.string.tutorial_tip_remote_pair)
    TechniqueId.CHUTE_REMOTE_PAIR_SINGLE -> AdvancedLessonCopy(
        R.string.tutorial_rule_chute_single, R.string.tutorial_reason_chute_single, R.string.tutorial_tip_chute_single)
    TechniqueId.CHUTE_REMOTE_PAIR_DOUBLE -> AdvancedLessonCopy(
        R.string.tutorial_rule_chute_double, R.string.tutorial_reason_chute_double, R.string.tutorial_tip_chute_double)
    TechniqueId.CHUTE_REMOTE_PAIR_BONUS -> AdvancedLessonCopy(
        R.string.tutorial_rule_chute_bonus, R.string.tutorial_reason_chute_bonus, R.string.tutorial_tip_chute_bonus)
    TechniqueId.SUE_DE_COQ_TYPE_1 -> AdvancedLessonCopy(
        R.string.tutorial_rule_sue_1, R.string.tutorial_reason_sue_1, R.string.tutorial_tip_sue_1)
    TechniqueId.SUE_DE_COQ_TYPE_2 -> AdvancedLessonCopy(
        R.string.tutorial_rule_sue_2, R.string.tutorial_reason_sue_2, R.string.tutorial_tip_sue_2)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_1M -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur1m, R.string.tutorial_reason_ur1m, R.string.tutorial_tip_ur1m)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_4M -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur4m, R.string.tutorial_reason_ur4m, R.string.tutorial_tip_ur4m)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_5P -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur5p, R.string.tutorial_reason_ur5p, R.string.tutorial_tip_ur5p)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_6 -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur6, R.string.tutorial_reason_ur6, R.string.tutorial_tip_ur6)
    TechniqueId.UNIQUE_RECTANGLE_TYPE_7 -> AdvancedLessonCopy(
        R.string.tutorial_rule_ur7, R.string.tutorial_reason_ur7, R.string.tutorial_tip_ur7)
    TechniqueId.NISHIO_FORCING_NET -> AdvancedLessonCopy(
        R.string.tutorial_rule_nishio_net, R.string.tutorial_reason_nishio_net, R.string.tutorial_tip_nishio_net)
    TechniqueId.DIGIT_FORCING_CHAIN -> AdvancedLessonCopy(
        R.string.tutorial_rule_digit_chain, R.string.tutorial_reason_digit_chain, R.string.tutorial_tip_digit_chain)
    TechniqueId.DIGIT_FORCING_NET -> AdvancedLessonCopy(
        R.string.tutorial_rule_digit_net, R.string.tutorial_reason_digit_net, R.string.tutorial_tip_digit_net)
    TechniqueId.STARFISH -> AdvancedLessonCopy(
        R.string.tutorial_rule_starfish, R.string.tutorial_reason_starfish, R.string.tutorial_tip_starfish)
    TechniqueId.WHALE -> AdvancedLessonCopy(
        R.string.tutorial_rule_whale, R.string.tutorial_reason_whale, R.string.tutorial_tip_whale)
    TechniqueId.LEVIATHAN -> AdvancedLessonCopy(
        R.string.tutorial_rule_leviathan, R.string.tutorial_reason_leviathan, R.string.tutorial_tip_leviathan)
    TechniqueId.EIGHT_Y_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_eight_y_wing, R.string.tutorial_reason_eight_y_wing, R.string.tutorial_tip_eight_y_wing)
    TechniqueId.NINE_Y_WING -> AdvancedLessonCopy(
        R.string.tutorial_rule_nine_y_wing, R.string.tutorial_reason_nine_y_wing, R.string.tutorial_tip_nine_y_wing)
    else -> error("No advanced tutorial text for $technique")
}
